#pragma once
#define YAML_CPP_STATIC_DEFINE
#include <cstdint>
#include <vector>
#include <asio.hpp>
#include <iostream>
#include <string>
#include <chrono>
#include <sstream>
#include <iomanip>
#include <ctime>
#include <map>
#include "nlohmann/json.hpp"
#include <fstream>
#include "yaml-cpp/yaml.h"
#include <filesystem>
#include <unordered_map>
#include <memory>
#include <mysql_driver.h>
#include <mysql_connection.h>
#include <cppconn/prepared_statement.h>
#include <cppconn/resultset.h>
#include <cppconn/statement.h>
#include <cppconn/exception.h>
#include <windows.h>
#include <queue>
#include <optional>
#include <csignal>
#include <stdexcept>
#include <functional>
#include <zlib.h>
#include <shared_mutex>
#include <atomic>
#include <thread>
#include <mutex>
#include <cstring>
#include <atomic>